#!/bin/sh

nixdir=$HOME/dotfiles/nixos

pushd $nixdir
vim . 
sudo nixos-rebuild switch --impure --flake $nixdir#default

gen=$(nixos-rebuild list-generations | grep current)
git add .
git commit -m "$gen"
git push
popd
