#!/bin/sh

nixdir=$HOME/dotfiles/nixos

pushd $nixdir
hx . 
sudo nixos-rebuild switch  --flake $nixdir#default
# or 
# sudo nixos-rebuild switch --flake $nixdir#nixos-desktop-vm

gen=$(nixos-rebuild list-generations | grep current)
git add .
git commit -m "$gen"
git push
popd
