#!/bin/sh

nixdir=$HOME/dotfiles/nixos

pushd $nixdir
sudo vim . 
sudo nixos-rebuild switch --flake $nixdir#default

gen=$(nixos-rebuild list-generations | grep current)
sudo git add .
sudo git commit -m "$gen"
popd
